const texts = [{text: "Kids, you tried your best and you failed miserably. The lesson is, never try.", author: "Homer Simpson"},
{text: "Facts are meaningless. You can use facts to prove anything that's even remotely true. Facts schmacts.", author: "Homer Simpson"},
{text: "I'm not popular enough to be different.", author: "Homer Simpson"},
{text: "As long as you're on TV people will respect you.", author: "Bart Simpson"},
{text: "You don't win friends with salad.", author: "Homer, Bart, and Marge Simpson"},
{text: "It takes two to lie. One to lie, and one to listen.", author: "Homer Simpson"},
{text: "Most of you will never fall in love, and marry out of fear of dying alone.", author: "Edna Krabappel"},
{text: "Family. Religion. Friendship. These are the three demons you must slay if you wish to succeed in business.", author: "Montgomery Burns"},
{text: "I'd rather let a thousand guilty men go free than chase after them.", author: "Chief Wiggum"},
{text: "Hi, I'm Troy McClure. You might remember me from such self-help videos as \"Smoke Yourself Thin\" and \"Get Confident, Stupid.\"", author: "Troy McClure"},
{text: "I used to be with it, but then they changed what \"it\" was, and now what I'm with isn't it. And what's \"it\" seems weird and scary to me", author: "Grandpa Simpson"},
{text: "But look! I got some cool pogs: Alf pogs! Remember Alf? He's back…in pog form!", author: "Milhouse Van Houten"},
{text: "A philanthropist. A humanitarian. A man of peace. These are just a few of the men who have come to spit on Montgomery Burns' grave", author: "Kent Brockman"},
{text: "Sit perfectly still. Only I may dance", author: "Conan O'Brien"},
{text: "Bake him away, toys.", author: "Chief Wiggum"},
{text: "My Homer is not a communist. He may be a liar, a pig, an idiot, a communist, but he is not a porn star.", author: "Grandpa Simpson"},
{text: "Another day, another box of stolen pens.", author: "Homer Simpson"},
{text: "Feels like I'm wearing nothing at all…nothing at all…nothing at all!", author: "Ned Flanders"},
{text: "Aren't we forgetting the true meaning of Christmas: the birth of Santa.", author: "Bart Simpson"},
{text: "I don't get mad, I get stabby.", author: "Fat Tony"},
{text: "Inflammable means flammable? What a country.", author: "Dr. Nick Riviera"},
{text: "Priceless like a mother's love, or the good kind of priceless?", author: "Bart Simpson"},
{text: "I don't mind if you pee in the shower, but only if you're taking a shower.", author: "Marge Simpson"},
{text: "Oh, loneliness and cheeseburgers are a dangerous mix.", author: "Comic Book Guy"},
{text: "Talking out of turn…that's a paddling. Looking out the window…that's a paddling. Staring at my sandals…that's a paddling. Paddling the school canoe…ooh, you better believe that's a paddling.", author: "Jasper"},
{text: "For the next five minutes, I'm going to party like it's on sale for $19.99.", author: "Apu Nahasapeemapetilon"},
{text: "Oh, dear God. Can't this town go one day without a riot?", author: "Mayor Quimby"},
{text: "My cat's breath smells like cat food.", author: "Ralph Wiggum"},
{text: "Well, if it isn't my old friend, Mr. McGreg, with a leg for an arm, and an arm for a leg.", author: "Dr. Nick Riviera"},
{text: "Everything's coming up Milhouse! ", author: "Milhouse Van Houten"},
{text: "I was saying \"Boo-urns.\" ", author: "Hans Moleman"},
{text: "To alcohol! The cause of, and solution to, all of life's problems.", author: "Homer Simpson"},
{text: "Your ideas are intriguing to me, and I wish to subscribe to your newsletter.", author: "Homer Simpson"},
{text: "I, for one, welcome our new insect overlords", author: "Kent Brockman"},
{text: "I've said it before and I'll say it again: democracy simply doesn't work.", author: "Kent Brockman"},
{text: "There's a 4:30 in the morning now?", author: "Bart Simpson"},
{text: "It's good for keepin' down the urges!", author: "Ned Flanders"},
{text: "Mrs. Krabappel and Principal Skinner were in the closet making babies and I saw one of the babies and then the baby looked at me", author: "Ralph Wiggum"},
{text: "Oh, I have had it, I have had it with this school, Skinner! The low test scores, class after class of ugly, ugly children", author: "Superintendent Chalmers"},
{text: "Hey kids, always recycle. TO THE EXTREME!", author: "Poochie"},
{text: "My eyes! The goggles do nothing!", author: "Rainier Wolfcastle"}]

export default texts;